/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/responses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createResponse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listJobs"];
    put?: never;
    post: operations["createJob"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getJobEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cancelJob"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}/approvals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["decideJobApproval"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/routes/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["previewRoute"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listModels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/{modelId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateModel"];
    trace?: never;
  };
  "/api/v1/quota": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getQuota"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUsage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAuditEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/retention/receipts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listDeletionReceipts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bootstrap/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["bootstrapApiKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listApiKeys"];
    put?: never;
    post: operations["createApiKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/keys/{id}/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["revokeApiKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/register/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["beginPasskeyRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/register/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verifyPasskeyRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/login/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["beginPasskeyLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/login/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verifyPasskeyLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/recovery/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["loginWithRecoveryCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      status: string;
      service: string;
    };
    CreateApiKeyRequest: {
      name: string;
      scopes: (
        "admin" | "jobs:read" | "jobs:write" | "quota:read" | "keys:write" | "approvals:write"
      )[];
      /** @default 60 */
      rateLimitPerMinute: number;
      /**
       * Format: date-time
       * @description Omit for the 30-day default; null requests a non-expiring administrator key
       */
      expiresAt?: string | null;
    };
    RevokeApiKeyRequest: {
      confirmationPrefix: string;
    };
    ApiKeyMetadata: {
      /** Format: uuid */
      id: string;
      name: string;
      prefix: string;
      scopes: string[];
      rateLimitPerMinute: number;
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: date-time */
      revokedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsedAt?: string | null;
    };
    CreatedApiKey: components["schemas"]["ApiKeyMetadata"] & {
      /** @description Plaintext API key returned only once */
      key: string;
      /** @description True when the same idempotent request is replayed */
      replayed?: boolean;
    };
    AuditEvent: {
      /** Format: uuid */
      id: string;
      actorId: string;
      action: string;
      resourceType: string;
      resourceId: string | null;
      metadata: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt: string;
    };
    DeletionReceipt: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      jobId: string;
      /** Format: date-time */
      payloadDeletedAt: string;
      /** Format: date-time */
      metadataDeleteAfter: string;
    };
    PermissionProfile: {
      /**
       * @default read
       * @enum {string}
       */
      filesystem: "none" | "read" | "write";
      /**
       * @default none
       * @enum {string}
       */
      network: "none" | "allowlist";
      allowedHosts?: string[];
      /** @default true */
      requireApprovalForWrites: boolean;
      /** @default true */
      requireApprovalForExternalActions: boolean;
    };
    TaskContract: {
      objective: string;
      /**
       * @default general
       * @enum {string}
       */
      taskKind: "bounded" | "coding" | "review" | "planning" | "batch" | "general";
      requiredContext?: string[];
      constraints?: string[];
      expectedOutput?: string;
      validation?: {
        responseSchema?: {
          [key: string]: unknown;
        };
        acceptanceTests?: string[];
      };
      /**
       * @default internal
       * @enum {string}
       */
      dataClassification: "public" | "internal" | "confidential" | "restricted";
      permissions?: components["schemas"]["PermissionProfile"];
      /** @default 120000 */
      deadlineMs: number;
      budget?: {
        maxCodexCredits?: number;
        /** @default 8192 */
        maxOutputTokens: number;
        /** @default 2 */
        maxAttempts: number;
      };
      sessionKey?: string;
      /** @default auto */
      model: string;
      /**
       * @default medium
       * @enum {string}
       */
      effort: "minimal" | "low" | "medium" | "high" | "xhigh";
      /** @default true */
      replayable: boolean;
      ambiguity?: number;
      risk?: number;
    };
    CreateJobRequest: {
      task: components["schemas"]["TaskContract"];
      metadata?: {
        [key: string]: string;
      };
    };
    Job: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status:
        | "accepted"
        | "queued"
        | "running"
        | "validating"
        | "succeeded"
        | "needs_review"
        | "failed"
        | "cancelled"
        | "expired";
      task: components["schemas"]["TaskContract"];
      route?: components["schemas"]["RouteDecision"] | null;
      output?: unknown;
      usage: components["schemas"]["UsageLedger"];
      validation?: unknown;
      errorCode?: string | null;
      errorMessage?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      expiresAt: string;
    };
    JobEvent: {
      id: string;
      /** Format: uuid */
      jobId: string;
      sequence: number;
      /** @enum {string} */
      type: "status" | "output.delta" | "tool" | "approval" | "validation" | "usage" | "error";
      data: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt: string;
    };
    RouteDecision: {
      /** @constant */
      provider: "codex";
      model: string;
      effort: string;
      policyVersion: string;
      reasonCode: string;
      /** @constant */
      sticky: true;
    };
    UsageLedger: {
      inputTokens: number;
      cachedInputTokens: number;
      outputTokens: number;
      /** @description Codex subscription credits calculated from the official credit rate card */
      codexCredits: number | null;
      /** @description Estimated token-only cost at official API rates; not an actual subscription charge */
      apiEquivalentUsd: number | null;
      /** @description Observed quota-window usage before the task */
      quotaUsedPercentBefore: number | null;
      /** @description Observed quota-window usage after the task */
      quotaUsedPercentAfter: number | null;
      /** @description Observed percentage-point change when both snapshots belong to the same quota window */
      quotaWindowDeltaPercent: number | null;
      allocatedSubscriptionUsd: number | null;
    };
    QuotaSnapshot: {
      /** @constant */
      provider: "codex";
      usedPercent: number | null;
      windowDurationMinutes: number | null;
      /** Format: date-time */
      resetsAt: string | null;
      planType: string | null;
      /** Format: date-time */
      fetchedAt: string;
      /** @enum {string} */
      source: "app-server" | "unavailable";
      stale: boolean;
      windows: components["schemas"]["QuotaWindow"][];
    };
    QuotaWindow: {
      id: string;
      name: string;
      /** @enum {string} */
      kind: "primary" | "secondary";
      usedPercent: number | null;
      remainingPercent: number | null;
      windowDurationMinutes: number | null;
      /** Format: date-time */
      resetsAt: string | null;
    };
    RuntimeModel: {
      id: string;
      displayName: string;
      available: boolean;
      enabled: boolean;
      hidden: boolean;
      isDefault: boolean;
      supportedReasoningEfforts: string[];
      defaultReasoningEffort: string | null;
      inputModalities: string[];
      creditRate: {
        [key: string]: unknown;
      } | null;
      apiRate: {
        [key: string]: unknown;
      } | null;
      /** @enum {string} */
      rateStatus: "available" | "unavailable";
      /** Format: date-time */
      discoveredAt: string;
    };
    ResponsesRequest: {
      /** @default auto */
      model: string;
      input: string | unknown[];
      instructions?: string;
      reasoning?: {
        /** @enum {string} */
        effort?: "minimal" | "low" | "medium" | "high" | "xhigh";
      };
      text?: {
        format?: {
          /** @enum {string} */
          type?: "text" | "json_schema";
          name?: string;
          schema?: Record<string, never>;
          strict?: boolean;
        };
      };
      /** @default false */
      stream: boolean;
      metadata?: {
        [key: string]: string;
      };
      max_output_tokens?: number;
    };
    Response: {
      id: string;
      /** @constant */
      object: "response";
      status: string;
      model: string;
      output?: unknown;
      error?: unknown;
      usage: components["schemas"]["UsageLedger"];
      metadata: Record<string, never>;
    };
    ErrorEnvelope: {
      error: {
        code: string;
        message: string;
        details?: unknown;
      };
    };
  };
  responses: {
    /** @description Unsupported parameter or invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Idempotency key reused with a different request digest */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Authentication failed or bootstrap is unavailable */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    IdempotencyKey: string;
    JobId: string;
    BootstrapToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service dependencies are ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  createResponse: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResponsesRequest"];
      };
    };
    responses: {
      /** @description Completed response or Server-Sent Events stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
          "text/event-stream": string;
        };
      };
      400: components["responses"]["BadRequest"];
      409: components["responses"]["Conflict"];
    };
  };
  listJobs: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent jobs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Job"][];
          };
        };
      };
    };
  };
  createJob: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateJobRequest"];
      };
    };
    responses: {
      /** @description Job accepted and queued */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      409: components["responses"]["Conflict"];
    };
  };
  getJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current job snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  getJobEvents: {
    parameters: {
      query?: {
        after?: number;
        stream?: boolean;
      };
      header?: never;
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Event collection or Server-Sent Events stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["JobEvent"][];
          };
          "text/event-stream": string;
        };
      };
    };
  };
  cancelJob: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested or terminal job returned */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
    };
  };
  decideJobApproval: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          decision: "approved" | "denied";
          reason?: string;
        };
      };
    };
    responses: {
      /** @description Approval decision recorded */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobEvent"];
        };
      };
    };
  };
  createBatch: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          requests: components["schemas"]["CreateJobRequest"][];
        };
      };
    };
    responses: {
      /** @description Jobs accepted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Job"][];
          };
        };
      };
    };
  };
  previewRoute: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          task: components["schemas"]["TaskContract"];
        };
      };
    };
    responses: {
      /** @description Deterministic route decision */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RouteDecision"];
        };
      };
    };
  };
  listModels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Runtime Codex model catalog merged with Router settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["RuntimeModel"][];
          };
        };
      };
    };
  };
  updateModel: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        modelId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          enabled: boolean;
        };
      };
    };
    responses: {
      /** @description Model setting updated or replayed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getQuota: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Latest worker-published quota snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuotaSnapshot"];
        };
      };
    };
  };
  getUsage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Codex Credits, API-equivalent estimates, and accepted-result totals */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            accepted_tasks: number;
            codex_credits: number;
            /** @description Estimated token-only cost at official API rates */
            api_equivalent_usd: number;
            credits_per_accepted_task: number | null;
            api_equivalent_usd_per_accepted_task: number | null;
            allocated_subscription_usd: number;
          };
        };
      };
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Administrative audit events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["AuditEvent"][];
          };
        };
      };
    };
  };
  listDeletionReceipts: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payload deletion receipts and metadata deletion deadlines */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["DeletionReceipt"][];
          };
        };
      };
    };
  };
  bootstrapApiKey: {
    parameters: {
      query?: never;
      header: {
        "X-Bootstrap-Token": components["parameters"]["BootstrapToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description First administrator API key, shown once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedApiKey"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listApiKeys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API key metadata without key digests */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ApiKeyMetadata"][];
          };
        };
      };
    };
  };
  createApiKey: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateApiKeyRequest"];
      };
    };
    responses: {
      /** @description API key metadata and one-time plaintext key */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedApiKey"];
        };
      };
    };
  };
  revokeApiKey: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevokeApiKeyRequest"];
      };
    };
    responses: {
      /** @description API key revoked */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            revoked: boolean;
            alreadyRevoked: boolean;
          };
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  beginPasskeyRegistration: {
    parameters: {
      query?: never;
      header: {
        "X-Bootstrap-Token": components["parameters"]["BootstrapToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName?: string;
        };
      };
    };
    responses: {
      /** @description WebAuthn registration challenge and browser options */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verifyPasskeyRegistration: {
    parameters: {
      query?: never;
      header: {
        "X-Bootstrap-Token": components["parameters"]["BootstrapToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          challengeId: string;
          response: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description Registration result and ten one-time recovery codes */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  beginPasskeyLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description WebAuthn authentication challenge and browser options */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verifyPasskeyLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          challengeId: string;
          response: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description Authentication result with an HttpOnly session cookie */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  loginWithRecoveryCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Authentication result after consuming one recovery code */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current application session revoked and cookie cleared */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            loggedOut: boolean;
          };
        };
      };
    };
  };
}
